name: Mirroring

on: [push]

jobs:
  to_gitlab:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: yesolutions/mirror-action@master
        with:
          REMOTE: 'https://github.com/admin-tsi/awsp-africa-client.git'
          GIT_USERNAME: admin-tsi
          GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
